services:
  - type: web
    name: monitor-noticias
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
